---
name: dev

concurrency: dev

on:
  push:
    branches:
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: .github/workflows/requirements.txt
      - name: Install Python requirements
        run: pip install -r .github/workflows/requirements.txt
      - name: Build cryptenv
        run: python -m build
