from typing import Final

UNSUPPORTED_PYTHON_VERSION: Final[int] = 1
INVALID_ENCRYPTED_PAYLOAD: Final[int] = 2
UNSUPPORTED_CRYPTENV_VERSION: Final[int] = 3
CONFIG_FILE_NOT_FOUND: Final[int] = 10
INVALID_ENV_FILE: Final[int] = 11
VARIABLE_NOT_FOUND: Final[int] = 12
DUPLICATE_VARIABLE_CLI: Final[int] = 13
PASSWORD_VALIDATION_FAILED: Final[int] = 14
ALREADY_ENCRYPTED_VARIABLE: Final[int] = 15
ERROR_READING_PASSWORD_FILE_CLI: Final[int] = 16
ERROR_READING_PASSWORD_FILE_ENV: Final[int] = 17
PASSWORD_FILE_ENV_NOT_SET: Final[int] = 18
NO_ARGUMENTS: Final[int] = 19
